### ISSUE TITLE
ValueError: Length of values does not match length of index

### ISSUE THREAD

**Issue by brianray** [Lilykos/clusterix#12]
Using the attached with settings: fields (Content), PCA, Euclidean, Count Vectorizer, k-means, 5 clusters.

```
(2017-10-12 08:31:54) - INFO	127.0.0.1 - - [12/Oct/2017 08:31:54] "POST /get_clustering_results HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/brray/Documents/Exxon/Demo/clusterix-master/src/routes/projections.py", line 17, in get_clustering_results
    return jsonify(**{'results': cluster_data(attrs)})
  File "/Users/brray/Documents/Exxon/Demo/clusterix-master/src/config.py", line 43, in wrapper
    return func(*args)
  File "/Users/brray/Documents/Exxon/Demo/clusterix-master/src/cluster/process.py", line 38, in cluster_data
    df['clx_cluster'] = labels
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/pandas/core/frame.py", line 2429, in __setitem__
    self._set_item(key, value)
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/pandas/core/frame.py", line 2495, in _set_item
    value = self._sanitize_column(key, value)
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/pandas/core/frame.py", line 2666, in _sanitize_column
    value = _sanitize_index(value, self.index, copy=False)
  File "/Users/brray/anaconda2/anaconda/envs/py3k/lib/python3.5/site-packages/pandas/core/series.py", line 2879, in _sanitize_index
    raise ValueError('Length of values does not match length of ' 'index')
ValueError: Length of values does not match length of index```

[out_emails_labled.csv.zip](https://github.com/Lilykos/clusterix/files/1379398/out_emails_labled.csv.zip)

**Comment by Lilykos** [comment]
Thank you for your issue! This version of Clusterix is not currently in development, but I have been working on an integrated version, with Jupyter Notebooks. If this is interesting to you, I can inform you when I have it available. Cheers!
